parameters:
    pim_import_export.manager.job_execution.class: Pim\Bundle\ImportExportBundle\Manager\JobExecutionManager
    pim_import_export.manager.job.class: Pim\Bundle\ImportExportBundle\Manager\JobManager

services:
    pim_import_export.manager.job_execution:
        class: %pim_import_export.manager.job_execution.class%
        arguments:
            - '@pim_import_export.repository.job_execution'
            - '@oro_security.security_facade'

    pim_import_export.manager.job:
        class: %pim_import_export.manager.job.class%
        arguments:
            - '@event_dispatcher'
            - '@pim_catalog.doctrine.smart_manager_registry'
