language: php
php:
    - "5.4"
    - "5.5"
    - "hhvm"

matrix:
    allow_failures:
        - php: "hhvm"

before_script:
    - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - php -r "readfile('https://getcomposer.org/installer');" | php
    - echo "extension=mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - sed -i '' 's/"require"/{"ext-mongo" : "*"},"require"/g' ./composer.json
    - hhvm composer.phar require --no-update doctrine/mongodb-odm v1.0.0-beta10@dev
    - hhvm composer.phar require --no-update doctrine/mongodb-odm-bundle v3.0.0-BETA6@dev
    - hhvm composer.phar update --prefer-dist --no-scripts --no-interaction

script:
    - ./bin/phpunit -c app/phpunit.travis.xml --testsuite PIM_Unit_Test
    - ./phpspec-fix
