parameters:
    pim_datagrid.datasource.result_record.hydrator.product.class:   Pim\Bundle\DataGridBundle\Datasource\ResultRecord\Orm\ProductHydrator
    pim_datagrid.datasource.result_record.hydrator.object_id.class: Pim\Bundle\DataGridBundle\Datasource\ResultRecord\Orm\ObjectIdHydrator
    pim_datagrid.datasource.result_record.hydrator.object.class:    Pim\Bundle\DataGridBundle\Datasource\ResultRecord\Orm\ObjectHydrator

services:
    pim_catalog.datasource.smart:
        class: %pim_datagrid.datasource.default.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@pim_datagrid.datasource.result_record.hydrator.default'
        tags:
            - { name: oro_datagrid.datasource, type: pim_datasource_smart }
