parameters:
    pim_base_connector.writer.direct_to_db.mongodb.product.class: Pim\Bundle\BaseConnectorBundle\Writer\DirectToDB\MongoDB\ProductWriter

services:
    pim_base_connector.writer.direct_to_db.mongodb.product:
        class: %pim_base_connector.writer.direct_to_db.mongodb.product.class%
        arguments:
            - '@pim_transform.transformer.mongodb.product'
            - '@pim_catalog.manager.product'
            - '@doctrine.odm.mongodb.document_manager'


