Pim\Bundle\CatalogBundle\Model\Completeness:
    type: embeddedDocument
    fields:
        id:
            id: true
        ratio:
            type: int
        missingCount:
            type: int
        requiredCount:
            type: int
        channel:
            type: entity
            targetEntity: Pim\Bundle\CatalogBundle\Model\ChannelInterface
        locale:
            type: entity
            targetEntity: Pim\Bundle\CatalogBundle\Model\LocaleInterface
